[functions.get-stream-match]
verify_jwt = false

[functions.get-stream-remote-match]
verify_jwt = false

[functions.get-nbv-calendar-ics]
verify_jwt = false

[functions.get-nbv-calendar]
verify_jwt = false

[functions.get-nbv-tournament-results]
verify_jwt = false
