create extension if not exists pgcrypto;

create table if not exists public.tournaments (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default '',
  players jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tournament_matches (
  id bigint generated by default as identity primary key,
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  client_id text not null default '',
  sort_order integer not null default 1,
  round_number integer not null default 1,
  table_number integer not null default 1,
  player_a text not null default '',
  player_b text not null default '',
  score_a integer,
  score_b integer,
  innings_a integer,
  innings_b integer,
  high_run_a integer,
  high_run_b integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tournament_matches_unique_client unique (tournament_id, client_id),
  constraint tournament_matches_unique_sort unique (tournament_id, sort_order)
);

alter table public.tournament_matches add column if not exists round_number integer not null default 1;
alter table public.tournament_matches add column if not exists table_number integer not null default 1;

create index if not exists idx_tournaments_owner_updated on public.tournaments(owner_user_id, updated_at desc);
create index if not exists idx_tournament_matches_tournament_sort on public.tournament_matches(tournament_id, sort_order);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_tournaments_touch_updated_at on public.tournaments;
create trigger trg_tournaments_touch_updated_at
before update on public.tournaments
for each row execute function public.touch_updated_at();

drop trigger if exists trg_tournament_matches_touch_updated_at on public.tournament_matches;
create trigger trg_tournament_matches_touch_updated_at
before update on public.tournament_matches
for each row execute function public.touch_updated_at();

alter table public.tournaments enable row level security;
alter table public.tournament_matches enable row level security;

drop policy if exists "tournaments_select_own_or_admin" on public.tournaments;
create policy "tournaments_select_own_or_admin"
on public.tournaments for select to authenticated
using (
  owner_user_id = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists "tournaments_insert_own_or_admin" on public.tournaments;
create policy "tournaments_insert_own_or_admin"
on public.tournaments for insert to authenticated
with check (
  owner_user_id = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists "tournaments_update_own_or_admin" on public.tournaments;
create policy "tournaments_update_own_or_admin"
on public.tournaments for update to authenticated
using (
  owner_user_id = auth.uid()
  or public.is_admin(auth.uid())
)
with check (
  owner_user_id = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists "tournaments_delete_own_or_admin" on public.tournaments;
create policy "tournaments_delete_own_or_admin"
on public.tournaments for delete to authenticated
using (
  owner_user_id = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists "tournament_matches_select_own_or_admin" on public.tournament_matches;
create policy "tournament_matches_select_own_or_admin"
on public.tournament_matches for select to authenticated
using (
  exists (
    select 1
    from public.tournaments t
    where t.id = tournament_matches.tournament_id
      and (
        t.owner_user_id = auth.uid()
        or public.is_admin(auth.uid())
      )
  )
);

drop policy if exists "tournament_matches_insert_own_or_admin" on public.tournament_matches;
create policy "tournament_matches_insert_own_or_admin"
on public.tournament_matches for insert to authenticated
with check (
  exists (
    select 1
    from public.tournaments t
    where t.id = tournament_matches.tournament_id
      and (
        t.owner_user_id = auth.uid()
        or public.is_admin(auth.uid())
      )
  )
);

drop policy if exists "tournament_matches_update_own_or_admin" on public.tournament_matches;
create policy "tournament_matches_update_own_or_admin"
on public.tournament_matches for update to authenticated
using (
  exists (
    select 1
    from public.tournaments t
    where t.id = tournament_matches.tournament_id
      and (
        t.owner_user_id = auth.uid()
        or public.is_admin(auth.uid())
      )
  )
)
with check (
  exists (
    select 1
    from public.tournaments t
    where t.id = tournament_matches.tournament_id
      and (
        t.owner_user_id = auth.uid()
        or public.is_admin(auth.uid())
      )
  )
);

drop policy if exists "tournament_matches_delete_own_or_admin" on public.tournament_matches;
create policy "tournament_matches_delete_own_or_admin"
on public.tournament_matches for delete to authenticated
using (
  exists (
    select 1
    from public.tournaments t
    where t.id = tournament_matches.tournament_id
      and (
        t.owner_user_id = auth.uid()
        or public.is_admin(auth.uid())
      )
  )
);
